site_name: SIBiLS
site_description: Swiss Institute of Bioinformatics Literature Services
site_url: https://sibils.github.io/
repo_url: https://github.com/sibils/sibils.github.io/
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - tables
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
theme:
  name: material
  palette:
    scheme: sibils
  logo: assets/sib.png
  custom_dir: overrides
  locale: en
  include_sidebar: false
  font: false
  features:
    - navigation.tabs
    - navigation.indexes
extra_css:
  - assets/extra.css
plugins:
  - social:
      cards: !ENV [CARDS, false]
      cards_color:
        fill: "#C40300"
        text: "#FFFFFF"

#### nav section ####
nav:
  - Quick Start: 'index.md'
  - Vocabularies: 'doc/vocabularies.md'
  - API:
    - 'fetch in MEDLINE': 'doc/api/fetch_medline.md'
    - 'fetch in PubMed Central': 'doc/api/fetch_pmc.md'
    - 'search in MEDLINE': 'doc/api/search_medline.md'
    - 'search in PubMed Central': 'doc/api/search_pmc.md'
  - 'Demo': https://denver.hesge.ch/SIBiLS/demo/
