site_name: SIBiLS
site_description: Swiss Institute of Bioinformatics Literature Services
site_url: https://sibils.org/
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - tables
  - footnotes
  - def_list
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
theme:
  name: material
  palette:
    scheme: sibils
  logo: assets/sib.png
  custom_dir: overrides
  locale: en
  include_sidebar: false
  font: false
  features:
    - navigation.tabs
    - navigation.indexes
    - content.code.copy       # ajouter un bouton "copier" à droite dans les blocs de code
extra_css:
  - assets/extra.css
extra:
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/#custom-site-analytics
  analytics:
    provider: custom

plugins:
  - swagger-ui-tag
  - bibtex:
      bib_file: "refs.bib"

#### nav section ####
nav:
  - 'Introduction': 'index.md'
  - 'Biodiversity PMC': 'biodiversitypmc/index.md'
  - 'BiotXplorer': 'biotxplorer/index.md'
  - 'Variomes': 'variomes/index.md'
  - 'SynVar': 'synvar/index.md'
  - 'Celltriage': 'celltriage/index.md'
  - 'SPARQL': 'sparql/index.md'
  - 'Collections':
    - 'SIBiLS collections': 'collections/sibils_collections.md'
    - 'upload publications in SIBiLS': 'collections/how_to_upload.md'
  - 'Vocabularies': 'vocabularies.md'
  - 'API':
    - 'API': 'api/index.md'
    - 'Biodiversity PMC':
      - 'Biodiversity PMC': 'api/biodiversitypmc/index.md'
      - 'Fetch': 'api/biodiversitypmc/fetch.md'
      - 'Search': 'api/biodiversitypmc/search.md'
      - 'QA': 'api/biodiversitypmc/qa.md'
      - 'Mapping ids': 'api/biodiversitypmc/mapping.md'
    - 'Celltriage': 'api/celltriage/index.md'
    - 'Variomes': 'api/variomes/index.md'
    - 'SynVar': 'api/synvar/index.md'
    - 'SPARQL': 'api/sparql/index.md'
  - 'SAB': 'sab.md'

