site_name: SIBiLS
site_description: Swiss Institute of Bioinformatics Literature Services
site_url: https://sibils.text-analytics.ch/
repo_url: https://github.com/sibils/
repo_name: github.com/sibils/
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - tables
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
theme:
  name: material
  palette:
    scheme: sibils
  logo: assets/sib.png
  custom_dir: overrides
  locale: en
  include_sidebar: false
  font: false
  features:
    - navigation.tabs
    - navigation.indexes
    - content.code.copy       # ajouter un bouton "copier" à droite dans les blocs de code
extra_css:
  - assets/extra.css

#### nav section ####
nav:
  - Introduction: 'index.md'
  - 'BiodiversityPMC':
      - 'BiodiversityPMC': "biodiversitypmc/index.md"
      - "Collections":
          - 'SIBiLS collections': 'biodiversitypmc/collections/sibils_collections.md'
          - 'upload publications in SIBiLS': 'biodiversitypmc/collections/how_to_upload.md'
      - "Vocabularies": 'biodiversitypmc/vocabularies.md'
      - "Videos": 'biodiversitypmc/videos.md'
      - "API":
          - 'fetch': 'biodiversitypmc/api/fetch.md'
          - 'search': 'biodiversitypmc/api/search.md'
          - 'qa': 'biodiversitypmc/api/qa.md'
          - 'SPARQL': 'biodiversitypmc/api/sparql.md'
  - "Variomes": 
    - "Variomes" : "variomes/index.md"
    - "Tutorial" : "variomes/tutorial.md"
  - "CellTriages": 
    - "CellTriages": "celltriages/index.md"
  - 'SAB': 'sab.md'
