name: ci 

on:
  push:
    branches:
      - biodiversitypmc 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        # see https://github.com/actions/checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        # see https://github.com/actions/setup-python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - uses: actions/cache@v4
        # see https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/#caching
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Install dependencies for the social plugin
        # see https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/#dependencies
        run: |
          sudo apt-get install -y libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev
          pip install pillow cairosvg
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
      - name: Build and deploy the branch gh-pages using mkdocs.publish.yml
        # https://www.mkdocs.org/user-guide/deploying-your-docs/
        run: mkdocs gh-deploy -f mkdocs.publish.yml --force --remote-branch gh-pages-sibils-org
      - name: Deploy on sibils.org
        # CURL options:
        # -f : GitHub workflow fail if the HTTP status code is not 200
        # see https://infra.text-analytics.ch/devdoc/tools/gh_update/
        # ${{ github.repository }} is replaced by the repository name, for example bitem-heg-geneve/bicikl-fair-data-place
        run: |
          curl -f -X 'POST' "https://infra.text-analytics.ch/api/webstatic/deploy/github.com/${{ github.repository }}/gh-pages-sibils-org" \
               -H 'accept: application/json' \
               -H 'Content-Type: application/x-www-form-urlencoded' \
               -d 'secret_key=${{secrets.SECRET_KEY}}'
